{{- if .Values.apiServer.enabled }}
{{- if .Values.apiServer.service.internal.enabled }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-internal-api-server
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: {{ .Values.image }}
          args: ["api-server"]
          env:
            - name: GIN_MODE
              value: release
{{- end -}}
{{- end }}