apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
  namespace: minio
type: Opaque
data:
  accesskey: bWluaW8= # base 64 encoded "minio" (echo -n 'minio' | base64)
  secretkey: bWluaW8xMjM= # based 64 encoded "minio123" (echo -n 'minio123' | base64)
---
apiVersion: miniocontroller.min.io/v1beta1
kind: MinIOInstance
metadata:
  name: dev
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio # Should match spec.metadata.labels
  ## Add metadata to the all pods created by the StatefulSet
  metadata:
    labels:
      app: minio
  replicas: 1
  credsSecret:
    name: minio-creds-secret
  requestAutoCert: false
---
