apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-worker
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: {{ .Values.image }}
          args: ["worker"]
