repositories:
  - name: istio
    url: https://storage.googleapis.com/istio-release/releases/{{ requiredEnv "ISTIO_VERSION" }}/charts
  - name: codecentric
    url: https://codecentric.github.io/helm-charts
  - name: zalando-pg
    url: https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator
  - name: banzaicloud-stable
    url: https://kubernetes-charts.banzaicloud.com
releases:
  - name: istio-init
    chart: istio/istio-init
    version: {{ requiredEnv "ISTIO_VERSION" }}
    namespace: istio-system
    values:
      - charts-config/istio/init.yaml

  - name: istio
    chart: istio/istio
    version: {{ requiredEnv "ISTIO_VERSION" }}
    namespace: istio-system
    values:
      - charts-config/istio/values.yaml

  - name: keycloak
    chart: codecentric/keycloak
    version: 7.5.0
    namespace: keycloak

  - name: postgres-operator
    chart: zalando-pg/postgres-operator
    version: 1.4.0
    namespace: postgres

  - name: vault-operator
    chart: banzaicloud-stable/vault-operator
    version: 1.2.1
    namespace: vault

  - name: minio
    chart: stable/minio
    version: 5.0.25
    namespace: minio