# apiVersion: v1
# kind: Service
# metadata:
#   name: minio-service
# spec:
#   type: ClusterIP
#   ports:
#     - port: 9000
#       targetPort: 9000
#       protocol: TCP
#   selector:
#     app: minio
# ---
apiVersion: miniocontroller.min.io/v1beta1
kind: MinIOInstance
metadata:
  name: dev
  namespace: my-minio-operator
spec:
  selector:
    matchLabels:
      app: minio # Should match spec.metadata.labels
  ## Add metadata to the all pods created by the StatefulSet
  metadata:
    labels:
      app: minio
  replicas: 1
  credsSecret:
    name: minio-creds-secret
  requestAutoCert: false